// Generated by CoffeeScript 1.3.3
(function() {

  describe("Util", function() {
    it("should map some values", function() {
      var array, results;
      array = [1, 2, 3];
      results = Util.map(array, function(item) {
        return item * 2;
      });
      return expect(results).toEqual([2, 4, 6]);
    });
    return it("should reduce some values", function() {
      var array, result;
      array = [1, 2, 3];
      result = Util.reduce(array, 0, function(acc, item) {
        return acc + item;
      });
      return expect(result).toEqual(6);
    });
  });

}).call(this);
