// Generated by CoffeeScript 1.3.3
(function() {

  this.Example = this.Example || {};

  this.Example.CoffeeUtil = (function() {

    function CoffeeUtil() {}

    CoffeeUtil.map = function(array, func) {
      var item, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        item = array[_i];
        _results.push(func(item));
      }
      return _results;
    };

    CoffeeUtil.reduce = function(array, acc, func) {
      var item, _fn, _i, _len;
      _fn = function(item) {
        return acc = func(acc, item);
      };
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        item = array[_i];
        _fn(item);
      }
      return acc;
    };

    return CoffeeUtil;

  })();

}).call(this);
