// Generated by CoffeeScript 1.3.3
(function() {

  this.CoffeeExample = this.CoffeeExample || {};

  this.CoffeeExample.PostCode = (function() {

    function PostCode(fromPostCode) {
      this.postCode = fromPostCode;
    }

    PostCode.prototype.toString = function() {
      return this.postCode;
    };

    return PostCode;

  })();

}).call(this);
