// Generated by CoffeeScript 1.3.3
(function() {
  var CoffeeUtil;

  CoffeeUtil = Example.CoffeeUtil;

  describe("CoffeeUtil", function() {
    it("should map some values", function() {
      var array, results;
      array = [1, 2, 3];
      results = CoffeeUtil.map(array, function(item) {
        return item * 2;
      });
      return expect(results).toEqual([2, 4, 6]);
    });
    return it("should reduce some values", function() {
      var array, result;
      array = [1, 2, 3];
      result = CoffeeUtil.reduce(array, 0, function(acc, item) {
        return acc + item;
      });
      return expect(result).toEqual(6);
    });
  });

}).call(this);
