// Generated by CoffeeScript 1.3.3
(function() {
  var PostCode;

  PostCode = this.CoffeeExample.PostCode;

  describe('PostCode', function() {
    return it('accepts a valid postcode', function() {
      var enteredPostCode, postcode;
      enteredPostCode = 'M1 1AA';
      postcode = new PostCode(enteredPostCode);
      return expect(postcode.toString()).toEqual('M1 1AA');
    });
  });

}).call(this);
